## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
sudo: required
services:
  - docker

env:
  matrix:
    - BINDEPS2_DOWNLOAD_ENGINE="curl"
    - BINDEPS2_DOWNLOAD_ENGINE="wget"

    # Also run the builder tests. They are not affected by the download or
    # compression engine runs, so no need to combinatorially explode the
    # testing space by looking at all combinations
    - BINDEPS2_RUN_BUILDER_TESTS="true"
matrix:
  allow_failures:
    - julia: nightly
  exclude:
    # Don't run builder tests on OSX
    - os: osx
      env: BINDEPS2_RUN_BUILDER_TESTS="true"

# Ironic.  He could provide binaries for others but not himself...
addons:
  apt:
    packages:
      - curl
      - wget
      - p7zip-full
      - tar
      - gzip

before_install:
  # If we're running the builder tests, go ahead and pull the latest crossbuild image
  - if [[ -n "$BINDEPS2_RUN_BUILDER_TESTS" ]]; then docker pull staticfloat/julia_workerbase:crossbuild-x64; fi

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BinDeps2")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
