## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # We don't have docker on OSX on travis at the moment...
  #- osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
sudo: required
services:
  - docker

matrix:
  allow_failures:
    - julia: nightly

# Ironic.  He could provide binaries for others but not himself...
addons:
  apt:
    packages:
      - curl
      - wget
      - p7zip-full
      - tar
      - gzip

before_install:
  # If we're running the builder tests, go ahead and pull the latest crossbuild image
  - docker pull staticfloat/julia_workerbase:crossbuild-x64
  # We need the bleeding edge of BinaryProvider.jl, just install that here now
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BinDeps2")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
