## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

env:
  matrix:
    - BINDEPS2_DOWNLOAD_ENGINE="curl"
    - BINDEPS2_DOWNLOAD_ENGINE="fetch"
    - BINDEPS2_DOWNLOAD_ENGINE="wget"
    - BINDEPS2_COMPRESSION_ENGINE="7z"
    - BINDEPS2_COMPRESSION_ENGINE="tar"
matrix:
  allow_failures:
    - julia: nightly

# Ironic.  He could provide binaries for others but not himself...
addons:
  apt:
    packages:
      - curl
      - wget
      - fetch
      - p7zip-full
      - tar
      - gzip

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BinDeps2")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
