## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # We don't have docker on OSX on travis at the moment...
  #- osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
sudo: required

matrix:
  allow_failures:
    - julia: nightly

env:
  global:
    - BINARYBUILDER_AUTOMATIC_APPLE=true
  matrix:
    - BINARYBUILDER_USE_SQUASHFS=true
    - BINARYBUILDER_USE_SQUASHFS=false

cache:
  directories:
    - deps/downloads

# Ironic.  He could provide binaries for others but not himself...
addons:
  apt:
    packages:
      - curl
      - wget
      - p7zip-full
      - tar
      - gzip

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BinaryBuilder")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Build docs
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("BinaryBuilder")); include(joinpath("docs", "make.jl"))'
